---
update-lists:
  stage: deploy
  image: ruby:3
  before_script:
    - git config user.name "GitLab CI Runner"
    - git config user.email "gitlab@example.com"
    - git checkout -b $CI_DEFAULT_BRANCH || true
    - git pull
  script:
    # install required dependencies
    - bundle install

    # fetch the last version of the blacklists
    - scripts/update-lists

    # update table in README file
    - bundle exec scripts/generate-readme < README.md.erb > README.md

    # push updates to git repository
    - scripts/sync-git
  only:
    - web
    - schedules
